#!/usr/bin/env python3
"""测试 tmux-skills 内部 legacy FMD 的抗干扰能力 - 不被长历史中的旧错误误导"""

import sys
sys.path.insert(0, '/Users/busiji/workbot/skills/tmux-skills/scripts')

from legacy_tmux_fmd_compat import classify_stop_reason, StopReason


def test_anti_interference():
    """测试抗干扰能力：长历史中的旧错误不应误导当前状态判断"""

    # 场景 1：长历史中有 Error/Traceback，但当前正常运行
    long_history_with_old_error = """
[1/30] Starting...
[2/30] Loading module A...
[3/30] Loading module B...
[4/30] Loading module C...
[5/30] Error: old error in history
[6/30] Traceback (most recent call last):
[7/30]   File 'old.py', line 10
[8/30]     old code error
[9/30] Recovered from error
[10/30] Continuing...
[11/30] Processing data batch 1...
[12/30] Processing data batch 2...
[13/30] Processing data batch 3...
[14/30] Processing data batch 4...
[15/30] Processing data batch 5...
[16/30] Saving results...
[17/30] Uploading to server...
[18/30] Syncing...
[19/30] Compressing...
[20/30] Archiving...
[21/30] Backing up...
[22/30] Verifying...
[23/30] Validating...
[24/30] Indexing...
[25/30] Reporting...
[26/30] Notifying...
[27/30] Cleaning up temp files...
[28/30] Releasing resources...
[29/30] Finalizing...
[30/30] Idle - waiting for next command
"""
    result, details = classify_stop_reason(long_history_with_old_error)
    assert result == StopReason.STILL_RUNNING, f"抗干扰失败：期望 still_running，实际 {result.value}"
    print("✓ 抗干扰测试 1 通过：长历史旧错误 + 当前正常 = STILL_RUNNING")

    # 场景 2：当前真的有错误，应该被检出
    current_error = """
[1/10] Starting...
[2/10] Loading...
[3/10] Processing...
[4/10] Error: Cannot find module 'foo'
"""
    result, details = classify_stop_reason(current_error)
    assert result == StopReason.FAULT, f"检出失败：期望 fault，实际 {result.value}"
    print("✓ 抗干扰测试 2 通过：当前真有错误 = FAULT")

    # 场景 3：当前真的有审批框，应该被检出
    current_sop = """
[1/10] Initializing...
[2/10] Loading config...
[3/10] This command requires approval
[4/10] 1. Yes
[5/10] 2. No
"""
    result, details = classify_stop_reason(current_sop)
    assert result == StopReason.SOP_APPROVAL, f"检出失败：期望 sop_approval，实际 {result.value}"
    print("✓ 抗干扰测试 3 通过：当前真有审批 = SOP_APPROVAL")

    # 场景 4：当前真的完成任务，应该被检出
    current_complete = """
[1/10] Processing...
[2/10] Computing...
[3/10] All tests passed
[4/10] Done
"""
    result, details = classify_stop_reason(current_complete)
    assert result == StopReason.TASK_COMPLETE, f"检出失败：期望 task_complete，实际 {result.value}"
    print("✓ 抗干扰测试 4 通过：当前真完成 = TASK_COMPLETE")

    print()
    print("所有抗干扰测试通过！")
    return 0


if __name__ == "__main__":
    raise SystemExit(test_anti_interference())
